#!/usr/bin/env node
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const pluginRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = path.join(pluginRoot, 'mcp', 'server.mjs');

const result = await build({
  absWorkingDir: pluginRoot,
  entryPoints: ['mcp/server.source.mjs'],
  outfile: outputPath,
  write: false,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: ['node18'],
  packages: 'bundle',
  treeShaking: true,
  minify: false,
  sourcemap: false,
  charset: 'utf8',
  legalComments: 'eof',
  banner: {
    js: [
      '#!/usr/bin/env node',
      '// Generated by scripts/build-mcp.mjs. Edit mcp/server.source.mjs or lib/, then rebuild.',
    ].join('\n'),
  },
  logLevel: 'warning',
});

const bundle = result.outputFiles.find((file) => file.path === outputPath);
if (!bundle) throw new Error(`esbuild did not produce ${outputPath}`);

// Some bundled dependency templates contain whitespace-only lines. Removing
// their trailing spaces keeps the committed artifact clean and reproducible.
const cleanBundle = bundle.text.replace(/[ \t]+$/gm, '');
await writeFile(outputPath, cleanBundle);
console.log(`Built ${path.relative(pluginRoot, outputPath)} (${Buffer.byteLength(cleanBundle)} bytes)`);
